version: '3'

services:

  postgres:
    image: postgres:14.3
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432
    container_name: postgres_test

volumes:
  db-data:
    driver: local
